name: "Scrap NFT volume"
on:
  schedule:
  - cron: "*/60 * * * *"
  workflow_dispatch: {}

jobs:
  scrap:
    runs-on: ubuntu-20.04
    permissions: write-all
    #container: bmogetta/volume_scrapper
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'      

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          echo "## Installed Requirements" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: execute py script # run volumen.py
        run: |
          python Topcollections/volumen.py
          echo "## Scrapping OpenSea" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Get current date
        id: date
        run: | 
          echo "JOB_DATE=$(date +'%Y-%m-%d %Hhs')" >> $GITHUB_ENV
          echo "## Getting job date and hour" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name : "Ensure trusted environment"
        run :  git config --global --add safe.directory /__w/Scraping_Opensea/Scraping_Opensea
      
      - name: "Add change name summary"
        run: |
          echo "## Commiting results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      - name: "Update commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "scrap: ${{ env.JOB_DATE }}"
          #commit_options: "--amend"
          push_options: "--force"
          skip_fetch: true
